title: Anees Shaikh # your name (or website title) here
logo: "professional_pic.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science, kickboxing, and a good cheesesteak  <br><br>
  <a href="https://www.linkedin.com/in/anees-shaikh-33a50382/">View My LinkedIn Profile</a> 
  <a href="https://github.com/shaikh23">View My Github Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
